### ISSUE TITLE
Collaborators Count Across Organization and Apps

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#148]
**Describe the bug**
Given the new 'Viewer' role, we're working to add some Collaborators to individual apps. If we add the same user to several apps, each addition counts against the number of Collaborators.

**To Reproduce**
1. Go to an app in your organization
2. Click 'People'
3. Add a collaborator that isn't currently in the Organization
4. Go to a different app in the same organization
5. Click 'People'
6. Add the same collaborator as in step #3
7. After the user accepts the invites, notice the Collaborator count has increased by 2

**Expected behavior**
An individual Collaborator only counts for 1 Collaborator against the Organization count limit regardless of the number of individual apps they're assigned to.

**Comment by CesarTrigo** [comment]
Hi @mkm12789 actually that is the expected behaviour since app users and organization users are right now separate entities on our side and could have different attributes based on the origin of the user (sso, social, tradicional logins) and also some other edge cases. However we are considering some alternatives to normalize and standardize the counts across the organizations. Will keep you posted once we make a decision.

**Comment by CesarTrigo** [comment]
Dear @mkm12789,
With today's release Organization Collaborators will count just one time across the entire organization, regardless of whether it was added to an App or to the entire Organization. Organization Collaborators counters have been recalculated accordingly. Please let us know if you find any issue or unexpected behaviour.
Thank you for your support @mkm12789 .
C.
