### ISSUE TITLE
Advanced User Management

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#150]
**Is your feature request related to a problem? Please describe.**
Now that our organization is up to 40+ apps, it's difficult to manage users who have access to individual apps as we have to open all of our apps to check permissions a single user may have.

**Describe the solution you'd like**
It would be nice to have a central location to easily manage all users. One way I can think of this with the way the site is currently built is, in the Organization's People page, list all Collaborators and Employees, including the ones that only have access to individual apps. A column would be added to the Collaborators and Employees table to show which apps the users have access to and we can filter the view based on those apps.
There is already an "Apps" header which makes me think this solution may already exist and doesn't work properly?

**Comment by CesarTrigo** [comment]
Hi @mkm12789,
We understand this requirement so we are analyzing the best potential implementation.
Some preliminary ideas from our side:

**Organization People level**
Create a centralized dashboard that allows you to see all users of the Org (whether they are users of the org or users of individual apps).

When selecting a user, a list of all the Apps to which they have permission will be shown, clearly displaying if the permissions come from the Org or the App and the role they have.

We are also analyzing the implementation of an Audit log (#154) under that section as well to provide some additional information about what the user is doing and how they interact with your organization.

**App People level**
All users who have access to an App must also be shown from the "People" section of the App itself. In this section you can see if the permission was created at App or Org level, as well as easily jump from a place to another.

Will keep you posted once decided but please know that we are prioritizing this, tentatively for end of Q1, beginning of Q2. I will share the final architecture here before proceeding so that we can get your feedback in advance.

**Comment by CesarTrigo** [comment]
Dear @mkm12789 
This feature has been fully implemented and will be deployed by today EOB. Now all Collaborators and Employees from the entire organization and Apps will be listed and could be managed from the Org. and the App.

A new "+ Add user" form has been also implemented to centralized also the process.

<img width="1509" alt="list" src="https://user-images.githubusercontent.com/453657/120220317-d60dff80-c23c-11eb-8b47-b02631203b0f.png">
<img width="598" alt="create" src="https://user-images.githubusercontent.com/453657/120220325-d908f000-c23c-11eb-86e3-8cbea3bf0f82.png">
