### ISSUE TITLE
Dashboard 'Search by Tag' Selection Issue

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#152]
**Describe the bug**
On an App's Build page in the Dashboard, when trying to search for a tag, if you use the mouse to select a tag (or finger on mobile) from the filtered suggestions, the populated result is the partial text you typed and some other tag. Using the keyboard and hitting 'Enter' seems to work fine but the mouse and finger selection has issues. This was produced using Chrome on a Mac as well as Chrome on iOS.
![95380589-cf8cdb00-089b-11eb-8080-8b5c3a7179b9 (1)](https://user-images.githubusercontent.com/1542685/106525331-ade1e000-6498-11eb-89a8-291753942f08.gif)

**Steps To Reproduce**
Visit and App's Build page.
Begin typing the name of a tag.
Select the tag from the list with your mouse.

**Expected Behavior**
The tag that is clicked on should be populated and only that on should be populated.

**Related Issue**
The Mouse/Finger selection is still an issue and is particularly problematic on mobile.
https://github.com/applivery/roadmap/issues/140

**Comment by CesarTrigo** [comment]
Hi @mkm12789 thank you for reporting this issue again.
Unfortunately the issue is not totally on the Applivery side but and is deeply connected with an existing issue of a component of the framework that we are using in the frontend of the Dashboard. Our team is actively working on a workaround so I will keep you posted with any update.

**Comment by CesarTrigo** [comment]
Dear @mkm12789,
We have just deployed a fix that should resolve this issue along with some other small improvements.
C.
