### ISSUE TITLE
Preventing (ios) enterprise app downloads from incompatible operating system versions.  

### ISSUE THREAD

**Issue by burak-pensa** [applivery/roadmap#170]
**Is your feature request related to a problem? Please describe.**
Our enterprise ios app could be downloaded by iPhones which their os versions are not listed as compatible. Ex. min required os version is 14.x.x but an iphone6 with os version 12.5.3 could download the app and stuck.

**Describe the solution you'd like**
Applivery could prevent download by disabling the download button with the incompatible os versions according to user-agent info.

**Describe alternatives you've considered**
[These guys](https://whatismyiosversion.com/) could establish determining OS version over browser. This could be used as proof that this could be done via user-agent info.

Thanks

**Comment by CesarTrigo** [comment]
Hi @burak-pensa, thank you very much for opening this feature request.
We will process it asap and consider it's implementation. For the reference, there is a similar ticket [#130] requesting to prevent the installation of iPhone Apps in iPads and vice versa.

Updates will be published here.

Best regards,
C.

**Comment by burak-pensa** [comment]
> Hi @burak-pensa, thank you very much for opening this feature request.
> We will process it asap and consider it's implementation. For the reference, there is a similar ticket [#130] requesting to prevent the installation of iPhone Apps in iPads and vice versa.
> 
> Updates will be published here.
> 
> Best regards,
> C.

Hi @CesarTrigo,

Any progress on the ticket?

Best Regards,

Burak

**Comment by burak-pensa** [comment]
@CesarTrigo we are still waiting for an update

**Comment by burak-pensa** [comment]
A kindly reminder for @CesarTrigo.

**Comment by CesarTrigo** [comment]
Dear @burak-pensa , this task is being finally prioritized.

The `.plist` parameter `UIDeviceFamily` will be processed in all new uploads. Previously uploaded builds will not be considered.

From the App Store perspective, incompatible devices (iPad or iPhone) will be notified that they might be installing an App that may not be compatible with their device. In order to prevent further issues, we will allow the users to attempt the installation anyway.

Related Apple documentation ca be found here:
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW10
<img width="1654" alt="UIDeviceFamily" src="https://user-images.githubusercontent.com/453657/140792727-d4e1b8d7-d66a-44b2-a83c-60aa5622f796.png">

**Comment by burak-pensa** [comment]
> Dear @burak-pensa , this task is being finally prioritized.
> 
> The `.plist` parameter `UIDeviceFamily` will be processed in all new uploads. Previously uploaded builds will not be considered.
> 
> From the App Store perspective, incompatible devices (iPad or iPhone) will be notified that they might be installing an App that may not be compatible with their device. In order to prevent further issues, we will allow the users to attempt the installation anyway.
> 
> Related Apple documentation ca be found here: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW10 <img alt="UIDeviceFamily" width="1654" src="https://user-images.githubusercontent.com/453657/140792727-d4e1b8d7-d66a-44b2-a83c-60aa5622f796.png">

@CesarTrigo I appreciate your effort on this issue, but I have a question though. Besides UIDeviceFamily, what about the allowed iOS version? 

Thanks, #burak

**Comment by CesarTrigo** [comment]
That will be accomplished through the validation of the following data in the cases where the Operative System version is available through the User Agent:

**iOS:**
- MinimumOSVersion

**Android:**
- MinSDKVersion: 14
- TargetSDKVersion: 28
